# Generated by Django 2.0.7 on 2018-07-18 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCurrencyOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=2, max_digits=19)),
                ('average_price_per_unit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.CryptoCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_day_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_week_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_month_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('three_month_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_year_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('all_time_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_day_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_week_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_month_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('three_month_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_year_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('all_time_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cryptocurrencies_owned', models.ManyToManyField(related_name='cryptocurrencies', through='App.CryptoCurrencyOwnership', to='App.CryptoCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=20, unique=True)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('exchange', models.CharField(default='', max_length=100)),
                ('industry', models.CharField(default='', max_length=100)),
                ('website', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=1000)),
                ('ceo', models.CharField(default='', max_length=100)),
                ('issueType', models.CharField(default='', max_length=50)),
                ('sector', models.CharField(default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('div_type', models.CharField(default='', max_length=50)),
                ('latest_actual_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('latest_estimated_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('latest_eps_year_ago', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('latest_eps_year_ago_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('latest_eps_year_ago_estimated_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('latest_fiscal_period', models.CharField(default='', max_length=100)),
                ('tminusone_actual_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusone_estimated_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusone_eps_year_ago', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusone_eps_year_ago_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusone_eps_year_ago_estimated_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusone_fiscal_period', models.CharField(default='', max_length=100)),
                ('tminustwo_actual_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminustwo_estimated_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminustwo_eps_year_ago', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminustwo_eps_year_ago_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminustwo_eps_year_ago_estimated_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminustwo_fiscal_period', models.CharField(default='', max_length=100)),
                ('tminusthree_actual_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusthree_estimated_eps', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusthree_eps_year_ago', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusthree_eps_year_ago_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusthree_eps_year_ago_estimated_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tminusthree_fiscal_period', models.CharField(default='', max_length=100)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=2, max_digits=19)),
                ('average_price_per_share', models.DecimalField(decimal_places=2, max_digits=19)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='SuperPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_day_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_week_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_month_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('three_month_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_year_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('all_time_performance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_day_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_week_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_month_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('three_month_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('one_year_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('all_time_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('owned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superportfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrencies_watched', models.ManyToManyField(related_name='cryptocurrencies_watched', to='App.CryptoCurrency')),
                ('owned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
                ('stocks_watched', models.ManyToManyField(related_name='stocks_watched', to='App.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='App.SuperPortfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stocks_owned',
            field=models.ManyToManyField(related_name='stocks', through='App.StockOwnership', to='App.Stock'),
        ),
        migrations.AddField(
            model_name='cryptocurrencyownership',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Portfolio'),
        ),
    ]
