# Generated by Django 2.0.7 on 2018-07-15 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_auto_20180715_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrencies_watched', models.ManyToManyField(related_name='cryptocurrencies_watched', to='App.CryptoCurrency')),
                ('owned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
                ('stocks_watched', models.ManyToManyField(related_name='stocks_watched', to='App.Stock')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='superportfolio',
            name='owned_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superportfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
