# Generated by Django 2.0.7 on 2018-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20180716_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='all_time_performance_amount',
            new_name='five_year_performance_amount',
        ),
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='all_time_performance_percent',
            new_name='five_year_performance_percent',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='all_time_performance_amount',
            new_name='five_year_performance_amount',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='all_time_performance_percent',
            new_name='five_year_performance_percent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ticker',
        ),
        migrations.AddField(
            model_name='stock',
            name='actual_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='ceo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='div_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='eps_year_ago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='eps_year_ago_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='eps_year_ago_estimated_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='estimated_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='issueType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='website',
            field=models.CharField(default='', max_length=250),
        ),
    ]
