# Generated by Django 2.0.7 on 2018-07-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20180716_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='actual_eps',
            new_name='latest_actual_eps',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='eps_year_ago',
            new_name='latest_eps_year_ago',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='eps_year_ago_change_percent',
            new_name='latest_eps_year_ago_change_percent',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='eps_year_ago_estimated_change_percent',
            new_name='latest_eps_year_ago_estimated_change_percent',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='estimated_eps',
            new_name='latest_estimated_eps',
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_fiscal_period',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusone_actual_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusone_eps_year_ago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusone_eps_year_ago_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusone_eps_year_ago_estimated_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusone_estimated_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusone_fiscal_period',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusthree_actual_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusthree_eps_year_ago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusthree_eps_year_ago_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusthree_eps_year_ago_estimated_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusthree_estimated_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminusthree_fiscal_period',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminustwo_actual_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminustwo_eps_year_ago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminustwo_eps_year_ago_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminustwo_eps_year_ago_estimated_change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminustwo_estimated_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='stock',
            name='tminustwo_fiscal_period',
            field=models.CharField(default='', max_length=100),
        ),
    ]
