# Generated by Django 2.0.7 on 2018-07-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20180717_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='five_year_performance_amount',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='five_year_performance_percent',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='last_updated_time',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_day_performance_amount',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_day_performance_percent',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_month_performance_amount',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_month_performance_percent',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_week_performance_amount',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_week_performance_percent',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_year_performance_amount',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='one_year_performance_percent',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='three_month_performance_amount',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='three_month_performance_percent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='five_year_performance_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='five_year_performance_percent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_day_performance_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_day_performance_percent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_month_performance_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_month_performance_percent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_week_performance_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_week_performance_percent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_year_performance_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='one_year_performance_percent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='three_month_performance_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='three_month_performance_percent',
        ),
    ]
