# Generated by Django 2.0.7 on 2018-07-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20180717_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='currency_name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
